/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package compi2_proyecto1_1s2016;

import java.awt.Dimension;
import java.awt.HeadlessException;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JViewport;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;

/**
 *
 * @author Mac
 */
public class Main extends javax.swing.JFrame {

    static analisis analizador;
    static int contadorTabs = 1;

    public static void compilarGramaticaJJ() {
        try {
            String[] cmd = new String[2];
            cmd[0] = "javacc";
            cmd[1] = "C://Users//Mac//Documents//NetBeansProjects//Compi2_Proyecto1_1s2016//src//compi2_proyecto1_1s2016//gramatica.jj";

            Runtime rt = Runtime.getRuntime();
            rt.exec(cmd);

        } catch (Exception ex) {
        }
    }

    public static void crearTab() {
        JScrollPane vertical = new JScrollPane();
        JTextArea console;
        vertical.setPreferredSize(new Dimension(jTabbedPane1.getWidth(), jTabbedPane1.getHeight()));
        console = new JTextArea(15, 15);
        vertical = new JScrollPane(console);
        vertical.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        jTabbedPane1.add(vertical, "Tab " + contadorTabs);
        contadorTabs++;
    }

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        crearTab();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultText = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("SF Atarian System", 0, 24)); // NOI18N
        jButton1.setText("Nueva Tab");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(60, 90, 170, 40);

        jTabbedPane1.setFont(new java.awt.Font("SF Atarian System", 0, 18)); // NOI18N
        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(20, 210, 680, 290);

        jButton2.setFont(new java.awt.Font("SF Atarian System", 0, 24)); // NOI18N
        jButton2.setText("Analizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(290, 90, 170, 40);

        jButton4.setFont(new java.awt.Font("SF Atarian System", 0, 24)); // NOI18N
        jButton4.setText("Abrir Archivo");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(60, 140, 170, 40);

        jLabel2.setFont(new java.awt.Font("SF Atarian System", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 73, 73));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("RESULTADO PARSEO");
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 0, 5, 5, new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(720, 0, 350, 80);

        jButton5.setFont(new java.awt.Font("SF Atarian System", 0, 24)); // NOI18N
        jButton5.setText("Ver Reportes");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(500, 140, 170, 40);

        jButton6.setFont(new java.awt.Font("SF Atarian System", 0, 24)); // NOI18N
        jButton6.setText("Inicializar Server");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(500, 90, 170, 40);

        jButton7.setFont(new java.awt.Font("SF Atarian System", 0, 24)); // NOI18N
        jButton7.setText("Guardar Archivo");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(290, 140, 170, 40);

        resultText.setColumns(20);
        resultText.setRows(5);
        jScrollPane1.setViewportView(resultText);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(733, 88, 320, 410);

        jLabel3.setFont(new java.awt.Font("SF Atarian System", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 73, 73));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("MENU");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 720, 80);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(715, 80, 5, 430);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 1070, 510);

        setSize(new java.awt.Dimension(1086, 549));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        crearTab();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Compi2_Proyecto1_1s2016.Precedencias = new ArrayList<>();
        Compi2_Proyecto1_1s2016.Tokens = new ArrayList<>();
        Compi2_Proyecto1_1s2016.auxConjuntos = new ArrayList<>();
        Compi2_Proyecto1_1s2016.TablaTransiciones = new ArrayList<>();
        Compi2_Proyecto1_1s2016.inicial = null;
        Compi2_Proyecto1_1s2016.Conjuntos = new ArrayList<>();
        Compi2_Proyecto1_1s2016.TablaSimbolos = new ArrayList<>();
        Compi2_Proyecto1_1s2016.Terminales = new ArrayList<>();
        Compi2_Proyecto1_1s2016.NoTerminales = new ArrayList<>();
        Compi2_Proyecto1_1s2016.auxIr_A = new ArrayList<>();
        Compi2_Proyecto1_1s2016.cadenaReturn = "";
        Compi2_Proyecto1_1s2016.cadenaErrores = "";

        System.out.println("--------------------------------------------------------------------------------");
        JViewport viewport = ((JScrollPane) (jTabbedPane1.getSelectedComponent())).getViewport();
        String sentence = ((JTextArea) viewport.getView()).getText();
        InputStream is = new ByteArrayInputStream(sentence.getBytes());
        if (analizador == null) {
            analizador = new analisis(is);
        } else {
            analizador.ReInit(is);
            resultText.setText("Analisis exitoso.");
        }
                    try {
            analizador.Input();
        } catch (Exception | Error e) {
            resultText.setText("Error en la entrada.\nDescripcion:\n\n" + e.getMessage());
        } finally {
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        JFileChooser csv;
        JFileChooser txt;
        String xStrPath = "";
        String[][] ArrayPrincipal, ArrayPrincipalCadena;
        int Rowc = 0;
        int Row = 0;
        int RowArch = 0;
        int RowCadena = 0;
        int Colc = 0;
        int Col = 0;
        File archivo = null;
        try {

            try {
                Scanner scanIn;
                String InputLine;

                csv = new JFileChooser();
                FileFilter filtro = new FileNameExtensionFilter("Archivo ix", "ix");
                csv.setFileFilter(filtro);
                csv.showOpenDialog(csv);
                archivo = csv.getSelectedFile();
                scanIn = new Scanner(new BufferedReader(new FileReader(archivo)));
                while (scanIn.hasNextLine()) {
                    InputLine = scanIn.nextLine();
                    String[] InArray = InputLine.split("");
                    Row++;
                    int colTemp = InArray.length;
                    if (colTemp > Col) {
                        Col = colTemp;
                    }
                }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
            JViewport viewport = ((JScrollPane) (jTabbedPane1.getSelectedComponent())).getViewport();
            ArrayPrincipal = new String[Row][Col];
            Scanner scanIn;
            String InputLine;
            try {
                scanIn = new Scanner(new BufferedReader(new FileReader(archivo)));
                while (scanIn.hasNextLine()) {
                    InputLine = scanIn.nextLine();
                    String[] InArray = InputLine.split("GGFDG2j");
                    System.arraycopy(InArray, 0, ArrayPrincipal[Rowc], 0, InArray.length);
                    Rowc++;
                }
                RowArch = Row;
                for (int i = 0; i < Row; i++) {
                    if (ArrayPrincipal[i][0] != null) {
                        ((JTextArea) viewport.getView()).setText(((JTextArea) viewport.getView()).getText() + ArrayPrincipal[i][0] + "\n");

                    }
                }
            } catch (FileNotFoundException | HeadlessException e) {
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Reportes.start();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
            TCPServer.startServer();
        } catch (Exception ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        JFileChooser txt;
        JViewport viewport = ((JScrollPane) (jTabbedPane1.getSelectedComponent())).getViewport();
        String temp = ((JTextArea) viewport.getView()).getText();
        int cont = 0;

        try {
            txt = new JFileChooser();
            txt.showSaveDialog(txt);
            File guarda = txt.getSelectedFile();
            if (guarda != null) {
                File output = new File(guarda + ".ix");
                FileWriter writer = new FileWriter(output);
                BufferedWriter buf = new BufferedWriter(writer);
                while (cont < temp.length()) {
                    if ("\n".equals(Character.toString(temp.charAt(cont)))) {
                        buf.write("\r");
                    }
                    buf.write(Character.toString(temp.charAt(cont)));
                    cont++;
                }
                buf.flush();
                buf.close();
                writer.close();
                JOptionPane.showMessageDialog(null, "El archivo se ha guardado exitosamente!",
                        "Información", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Su archivo no se ha guardado",
                    "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void start() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea resultText;
    // End of variables declaration//GEN-END:variables
}
